# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ dev ]
  

jobs:
  test:
    name: Test on mode ${{matrix.os}} and {{matrix.node}}
    
     
    runs-on: ${{matrix.os}}

    strategy:
      matrix:
        node: [10.x, 12.x, 14.x]
        os: [windows-latest,macOS-latest ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{matrix.node}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node}}
        
    - name: Install dependencies
      run: |
         npm install
      
    - name: Lint files 
      run : |
          npm run lint
    - name: build
      run: |
        npm run build
    - name: build
      run: |
        npm run build    
    - name: test
      run: |
        npm test
