# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the tesing branch
on:
  push:
    branches: [ dev]
  

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
 test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [10.x,12.x,14.x]
        os: [ubuntu-latest,windows-latest, macOS-latest]     

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name:   Use Node.js ${{matrix.node}}
      uses: actions/setup-node@v1
      with:
        node-version: ${{matrix.node}}

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Install Dependencies
      run: |
        npm install
    - name: eslint tesing
      run: |
        npm run lint
    - name: build
      run: |
        npm run build
    - name: unit testing
      run: |
        npm run test
